level-07/college_portal/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root to: "static_pages#index"
	resources :departments, only: [:index, :create, :new]
	resources :sections, only: [:index, :new, :create]
	resources :students, only: [:index, :new, :create, :show]
end

level-07/college_portal/app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
	def index
	 @departments=Department.all
	end
	def new
   	 @department = Department.new
  	end

 	 def create
   	 @department = Department.new(department_params)
    	if @department.save
     	 redirect_to action: "index"
   	 else
    	  render "new"
 	   end
 	 end

  private

  def department_params
    params[:department].permit(:name)
  end
end

level-07/college_portal/app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
    if params[:department_id]
      @sections = Section.where(department_id: params[:department_id]).all
    else
      @sections = Section.all
    end
  end

  def new
    @section = Section.new
    @department_collection = Department.all.collect { |p| [p.name, p.id] }
  end

  def create
    @section = Section.new(section_params)
    if @section.save
      redirect_to action: "index"
    else
      render "new"
    end
  end

  private

  def section_params
    params[:section].permit(:name, :department_id)
  end
end

level-07/college_portal/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    if params[:department_id].present? && params[:section_id].present?
      @students = Student.where(department_id: params[:department_id],section_id: params[:section_id]).all
    else
      @students = Student.all
    end
  end
  def show
      @student = Student.where(id: params[:id])	
      @department=Department.all
      @sectionval=Section.all
  end
  
  def new
      @student=Student.new
      @department_collection=Department.all.collect { |p| [p.name, p.id] }
      @section_collection=Section.all.collect { |p| [p.name, p.id , p.department_id] }
  end
  def create
      @student = Student.new(student_params)

    if @student.save
      redirect_to action: "index"
    else
      flash[:danger] = @student.errors.values.join(', ')
      redirect_to action: "new"
    end
  end

  private

  def student_params
    params[:student].permit( :name,:roll_no, :email, :section_id, :department_id)
  end
end

level-07/college_portal/app/views/departments/index.html.erb
<div class="row">
  <div class="col-md-10">
    <h2>Departments</h2>
  </div>
  <div class="col-md-2">
    <a class="btn btn-primary float-right" href="<%= new_department_path %>" role="button">Create</a>
  </div>
</div>

<br/>

<ul class="list-group">
  <% @departments.each do |department| %>
  <li class="list-group-item"><a href="<%= sections_path(department_id: department.id) %>"><%= department.name %></a></li>
  <% end %>
</ul>

level-07/college_portal/app/views/sections/index.html.erb
<div class="row">
  <div class="col-md-10">
    <h2>Sections</h2>
  </div>
  <div class="col-md-2">
    <a class="btn btn-primary float-right" href="<%= new_section_path %>" role="button">Create</a>
  </div>
</div>

<br/>

<ul class="list-group">
  <% @sections.each do |section| %>
    <li class="list-group-item"><a href="<%= students_path(department_id: section.department_id,section_id: section.id) %>"><%= section.name %></a></li>
  <% end %>
</ul>