project-code/m-i-projectapptwo/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root to: "static_pages#index"
   resources :blog_posts, only: [:index, :create, :new, :show, :update]
   resources :github, only: [:index]
   resources :twitter, only: [:index]
   resources :comments, only: [:index, :create, :new]
end

project-code/m-i-projectapptwo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

project-code/m-i-projectapptwo/app/models/blog_post.rb
class BlogPost < ApplicationRecord 
  has_many :comments, dependent: :destroy
  before_save :like_count
  private
  def like_count
    if self.likes.nil?
     self.likes=0
    end
    self.likes=self.likes+1
  end
end

project-code/m-i-projectapptwo/app/models/comment.rb
class Comment < ApplicationRecord
 belongs_to :user
 belongs_to :blog_post
 
end

project-code/m-i-projectapptwo/app/models/repository.rb
class Repository < ApplicationRecord
end

project-code/m-i-projectapptwo/app/models/tweet.rb
class Tweet < ApplicationRecord
end

project-code/m-i-projectapptwo/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments,dependent: :destroy
end

project-code/m-i-projectapptwo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

project-code/m-i-projectapptwo/app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!
  def index
    @blogs=BlogPost.all
  end
  def new
   unless current_user.admin?
    flash[:danger] = "You are not allowed to access this page."
    redirect_to root_path
   end
    @blogs = BlogPost.new
  end
  def show
      @blogs = BlogPost.where(id: params[:id])	
      @comments= Comment.where(blog_post_id: params[:id])
      @users=User.all
      @blog = BlogPost.find_by_id(params[:id])
  end

  def update
  unless current_user.admin?
    flash[:danger] = "You are not allowed to access this page."
    redirect_to root_path
  end
    @blog = BlogPost.find_by_id(params[:id])
    if @blog.save
      redirect_to blog_posts_path
    else
      render "show"
    end
  end
  
  def create
  unless current_user.admin?
    flash[:danger] = "You are not allowed to access this page."
    redirect_to root_path
  end
    @blogs = BlogPost.new(blog_params)
    if @blogs.save
      redirect_to action: "index"
    else
      render "new"
    end
  end

  private

  def blog_params
    params[:blog_post].permit( :title, :content )
  end
 
end

project-code/m-i-projectapptwo/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end
  def new 
    @comments=Comment.new
   @user_collection=User.all.collect { |p| [p.email, p.id] }
   @blog_collection=BlogPost.all.collect { |p| [p.title, p.id ] }
  end
  def create
    @comments = Comment.new(comment_params)
    if @comments.save
      redirect_to blog_posts_path
    else
      render "new"
    end
  end
   private

  def comment_params
    params[:comment].permit( :content, :user_id, :blog_post_id)
  end
end

project-code/m-i-projectapptwo/app/controllers/github_controller.rb
class GithubController < ApplicationController
 before_action :authenticate_user!
 def index
  require 'github_api'
 
  github = Github.new

  @repos_from_github = github.repos.list(user: 'MamathaYarramaneni')

 end
end

project-code/m-i-projectapptwo/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
 def index 
  @blogs=BlogPost.all
 end
end

project-code/m-i-projectapptwo/app/controllers/twitter_controller.rb
class TwitterController < ApplicationController
  before_action :authenticate_user!
  def index
	require 'twitter'

	client = Twitter::REST::Client.new do |config|
	  config.consumer_key = "AUHNJbJKyzqk10Sb7QjXuNoMD"
	  config.consumer_secret = "c1bjwh5LS7ezYlSgMjlV7ekcfVOAJSvvhGf2cL5wKsGCBxcdXN"
	  config.access_token = "1171088394413211648-bYHxSb1cTBOYubLI5p6033VWVgcy8M"
	  config.access_token_secret = "GLBYWMcUGk17uRSm3EqJLhhI1JUbSdULT0zQT3BGHozlj"
	end

	@timeline = client.user_timeline("MamathaYarrama1")

  end
end

project-code/m-i-projectapptwo/app/helpers/application_helper.rb
module ApplicationHelper
end

project-code/m-i-projectapptwo/app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

project-code/m-i-projectapptwo/app/helpers/comments_helper.rb
module CommentsHelper
end

project-code/m-i-projectapptwo/app/helpers/github_helper.rb
module GithubHelper
end

project-code/m-i-projectapptwo/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

project-code/m-i-projectapptwo/app/helpers/twitter_helper.rb
module TwitterHelper
end

project-code/m-i-projectapptwo/app/views/comments/new.html.erb
<h2>Comment here</h2>

<%= form_for(@comments) do |f| %>
  <div class="form-group">
  
   <label>Description</label>
    <%= f.text_area :content, class: "form-control", placeholder: "description", required: true %><br/>
   <br/>
    <label>User</label>
    <%= f.select :user_id, @user_collection, { prompt: 'Select User' }, class: "form-control", required: true%>
    <br/>
     <label>Blog</label>
    <%= f.select :blog_post_id, @blog_collection, { prompt: 'Select Blog' }, class: "form-control", required: true%>
    <br/>
    <%= f.submit text: "create", class: "btn btn-dark" %>
  </div>
<% end %>

project-code/m-i-projectapptwo/app/views/github/index.html.erb
  <div class="row" style="margin-top:20px">
    <div class="col-md-1 float-left ">
 	<%= image_tag("github.png", :alt => "rss feed", :size => '50x50') %> 
    </div>
    <div class="col-md-10"><h2>My Github Repos!</h2></div>
   
  </div>
   </br>

  <%  @repos_from_github.each do |repo| %>
 <ul class="card" style="background-color: #EBEBEB;font-size:20px; margin-bottom:20px;" >
  <li class="card-body" >
   <div class="col-md-12 " >
     <%= repo.name %>
   </div>
    <div class="col-md-12 " >
    <a href="#">   <%= repo.url %></a>
   </div>
    <div class="col-md-12 " >
     <%= repo.stargazers_count %> stars
   <div>
  </li>
  </ul>
   <% end %>

project-code/m-i-projectapptwo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MIBlogproject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "style" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%=root_path%>">M-I-BLOG</a>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="<%=root_path%>">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="<%= blog_posts_path %>">Blogs</a>
      </li>
       <li class="nav-item ">
        <a class="nav-link" href="<%= github_index_path %>">GitRepos</a>
      </li>
	 <li class="nav-item ">
        <a class="nav-link" href="<%= twitter_index_path %>">Tweets</a>
      </li>
    </ul>
  </div>
   <span class="navbar-text text-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong> |
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
</span>
</nav>

<!-- The yield statement is where views rendered by actions will be inserted. -->
<div class="container">
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
    <% elsif alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% else %>
    <% flash.each do |key, value| %>
      <%= content_tag(:p, value, class: "alert alert-#{key}") %>
    <% end %>
  <% end %>

  <%= yield %>
</div>

<footer class="page-footer font-small bg-dark">
  <div class="footer-copyright text-center py-3 text-light">(c) 2019 Indupriya_M  Mamatha_Y
  </div>
</footer>
</body>
</html>

project-code/m-i-projectapptwo/app/views/static_pages/index.html.erb
<%= stylesheet_link_tag "style" %>
<div class="jumbotron" style="background-color: #B9EFF4; margin-top:50px;">
  <h1 class="display-3">Hey there Everyone!</h1>
  <p class="lead">This is a blog showcasing our interests</p>
  <hr class="my-4">
 
  
  
 
 <div class="row" style="margin-top:20px">
   <div class="col-md-1 float-left ">
 	 <%= image_tag("yinyang.png", :alt => "rss feed", :size => '50x50') %>
    </div>
  <div class="col-md-8">
    <h2>My Blogs!</h2>
  </div>

  <div class="col-md-2">
    <a class="btn btn-dark float-right" href="<%= blog_posts_path  %>" role="button">Check out!</a>
  </div>
  
</div>

<br/>
 <div class="row" style="margin-top:20px">
   <div class="col-md-1 float-left ">
 	<%= image_tag("gith.png", :alt => "rss feed", :size => '50x50') %> 
    </div>
  <div class="col-md-8">
    <h2>My Github Repos!</h2>
  </div>

  <div class="col-md-2">
    <a class="btn btn-dark float-right" href="<%= github_index_path  %>" role="button">Check out!</a>
  </div>
  
</div>
 
<br/>
 <div class="row" style="margin-top:20px">
   <div class="col-md-1 float-left ">
 	<%= image_tag("twit.png", :alt => "rss feed", :size => '55x55') %> 
    </div>
  <div class="col-md-8">
    <h2>My Tweets!</h2>
  </div>

  <div class="col-md-2">
    <a class="btn btn-dark float-right" href="<%= twitter_index_path  %>" role="button">Check out!</a>
  </div>
  
</div>
 
</div>

project-code/m-i-projectapptwo/app/views/twitter/index.html.erb
   <div class="row" style="margin-top:20px">
    <div class="col-md-1 float-left ">
 	<%= image_tag("twit.png", :alt => "rss feed", :size => '55x55') %> 
    </div>
    <div class="col-md-10"><h2>My Tweets!</h2></div>
   
  </div>
   </br>
 <%  @timeline.each do |tweet| %>    
   <ul class="card" style="background-color: #EBEBEB;font-size:20px; margin-bottom:20px;">

 
  <li class="card-body">
   <div class="col-md-12 " >
     <%= tweet.text %>
   </div>
    <div class="col-md-12 " >
     <%= tweet.retweet_count %> retweets
   </div>
  </li>
  </ul>
   <% end %>